version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      GOTRACEBACK: single
    ports:
      - "80:8080"
  
  emailservice:
    build:
      context: ./src/emailservice
      dockerfile: Dockerfile
    ports:
      - "5000:8080"

  currencyservice:
    build:
      context: ./src/currencyservice
      dockerfile: Dockerfile
    ports:
      - "7000:7000"

  checkoutservice:
    build:
      context: ./src/checkoutservice
      dockerfile: Dockerfile
    ports:
      - "5050:5050"

  cardservice:
    build:
      context: ./src/cartservice/src
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    depends_on:
      - frontend

  ad-service:
    build:
      context: ./src/adservice/
      dockerfile: Dockerfile
    ports:
      - "9555:9555"

  loadgenrator:
    build:
      context: ./src/loadgenerator
      dockerfile: Dockerfile

  paymentservice:
    build:
      context: ./src/paymentservice
      dockerfile: Dockerfile
    ports:
      - "50051:50051"

  productcatalogservice:
    build:
      context: ./src/productcatalogservice
      dockerfile: Dockerfile
    ports:
      - "3550:3550"
  
  recommendationservice:
    build:
      context: ./src/recommendationservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  shippingservice:
    build:
      context: ./src/shippingservice
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
