trigger:
  branches:
    include:
    - master
# no PR triggers
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build stage
    jobs:  
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
 
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js' 
      # - task: SonarCloudPrepare@1
      #   inputs:
      #     SonarCloud: 'sonarcloudconnection'
      #     organization: 'leonidsconsultants0154'
      #     scannerMode: 'CLI'
      #     configMode: 'manual'
      #     cliProjectKey: 'leonidsconsultants0154_trayistatapp'
      #     cliProjectName: 'trayistatapp'
      #     cliSources: '.'
          
      - script: |
          npm install
        displayName: 'npm install' 
      
      # - task: SonarCloudAnalyze@1

      # - task: SonarCloudPublish@1
      #   inputs:
      #     pollingTimeoutSec: '300'
          
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        artifact: drop